/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "In2.h"
#include "In2_aliases.h"
#include "In1.h"
#include "In1_aliases.h"
#include "Out1_1.h"
#include "Out1_1_aliases.h"
#include "Out1_2.h"
#include "Out1_2_aliases.h"
#include "Out1_3.h"
#include "Out1_3_aliases.h"
#include "Out1_4.h"
#include "Out1_4_aliases.h"
#include "Result.h"
#include "Result_aliases.h"
#include "In1_2.h"
#include "In1_2_aliases.h"
#include "In2_2.h"
#include "In2_2_aliases.h"
#include "Out2_1.h"
#include "Out2_1_aliases.h"
#include "Out2_2.h"
#include "Out2_2_aliases.h"
#include "Out2_3.h"
#include "Out2_3_aliases.h"
#include "Out2_4.h"
#include "Out2_4_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

